
--JoinBoard

INSERT INTO JOINBOARD (RESEQ, MSEQ, JSUBJECT, JCONTENT, JSTART, JEND, JCOUNT, JREGDATE, ACTIVESTATE)
    VALUES (RESEQ.nextval, 68, '스프링프로젝트', '스프링+마이바티스로 프로젝트 진행하려 합니다.', '2017-10-01', '2017-10-20', 4, '2017-09-25', 'n');

COMMIT;

SELECT * FROM vjoinTeam;

DROP VIEW JOINTEAM;

CREATE OR REPLACE VIEW vjoinTeam
AS
 SELECT jb.*,m.MNAME FROM JOINBOARD jb
    INNER JOIN MEMBER m
     ON jb.MSEQ = m.MSEQ;