-- 회원메뉴
COMMIT ;

--공지여부
INSERT INTO NOTICESTATE VALUES (0, 'n');
INSERT INTO NOTICESTATE VALUES (1, 'y');

--승인통과
INSERT INTO APPROVE VALUES (0, '미승인');
INSERT INTO APPROVE VALUES (1, '승인');
INSERT INTO APPROVE VALUES (2, '거절');
INSERT INTO APPROVE VALUES (3, '탈퇴');
INSERT INTO APPROVE VALUES (4, '취소');

--공개여부3
INSERT INTO OPENSTATE VALUES (0, '비공개');
INSERT INTO OPENSTATE VALUES (1, '공개');
INSERT INTO OPENSTATE VALUES (2, '삭제');




